### ISSUE TITLE
Unable to view traffic on vnet1 interface

### ISSUE THREAD

**Issue by UzairJawaid** [open-traffic-generator/ixia-c#67]
I am running quickstart_snappi application. i am able to monitor packets on veth2 interface using tcpdump. but its not showing anything on vet1. I am also receiving wrong port_metric stats. i am transmitting 1000 packets of 128 byte size which i am receiving on tcpdump but getting stats bytes_tx = 384. 

![image](https://user-images.githubusercontent.com/19300480/161245203-747e7d34-9149-48a0-b66d-5f7fa75444b0.png)

**Comment by ashutshkumr** [comment]
@UzairJawaid
- It's a known limitation when running tcpdump to check out-bound frames on network interfaces (when generating traffic using ixia-c). Currently tcpdump will only show in-bound frames on network interfaces.
- For the second issue, could you please modify the script to dump port metrics after a wait for 1 second ? To keep the script very minimal, we only dump it once, as soon as we start traffic - this results in intermediate metrics being dumped (instead of final metrics)

**Comment by UzairJawaid** [comment]
Thanks.
Yes the second issue resolved the same way. i added few lines from hello_snappi.py  and it worked
